tinymce.addI18n('pt_PT',{
"Cut": "Cortar",
"Heading 5": "Cabeçalho 5",
"Header 2": "Cabeçalho 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "O seu navegador não suporta acesso direto à área de transferência. Por favor use os atalhos de teclado Ctrl+X\/C\/V.",
"Heading 4": "Cabeçalho 4",
"Div": "Div",
"Heading 2": "Cabeçalho 2",
"Paste": "Colar",
"Close": "Fechar",
"Font Family": "Fonte",
"Pre": "Pre",
"Align right": "Alinhar à direita",
"New document": "Novo documento",
"Blockquote": "Bloco de citação",
"Numbered list": "Lista numerada",
"Heading 1": "Cabeçalho 1",
"Headings": "Cabeçalhos",
"Increase indent": "Aumentar avanço",
"Formats": "Formatos",
"Headers": "Cabeçalhos",
"Select all": "Selecionar tudo",
"Header 3": "Cabeçalho 3",
"Blocks": "Blocos",
"Undo": "Desfazer",
"Strikethrough": "Rasurado",
"Bullet list": "Lista com marcadores",
"Header 1": "Cabeçalho 1",
"Superscript": "Superior à linha",
"Clear formatting": "Limpar formatação",
"Font Sizes": "Tamanhos de fonte",
"Subscript": "Inferior à linha",
"Header 6": "Cabeçalho 6",
"Redo": "Refazer",
"Paragraph": "Parágrafo",
"Ok": "Ok",
"Bold": "Negrito",
"Code": "Código",
"Italic": "Itálico",
"Align center": "Alinhar ao centro",
"Header 5": "Cabeçalho 5",
"Heading 6": "Cabeçalho 6",
"Heading 3": "Cabeçalho 3",
"Decrease indent": "Diminuir avanço",
"Header 4": "Cabeçalho 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "A opção colar está em modo de texto simples. O conteúdo será colado como texto simples até desativar esta opção.",
"Underline": "Sublinhado",
"Cancel": "Cancelar",
"Justify": "Justificado",
"Inline": "Em linha",
"Copy": "Copiar",
"Align left": "Alinhar à esquerda",
"Visual aids": "Ajudas visuais",
"Lower Greek": "Gregas minúsculas",
"Square": "Quadrado",
"Default": "Predefinição",
"Lower Alpha": "Alfas minúsculas",
"Circle": "Círculo",
"Disc": "Disco",
"Upper Alpha": "Alfas maiúsculas",
"Upper Roman": "Romanos maiúsculos",
"Lower Roman": "Romanos minúsculos",
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "O ID deve começar com uma letra, seguido apenas por letras, números, hífens, pontos, dois pontos ou underscores.",
"Name": "Nome",
"Anchor": "Âncora",
"Id": "ID",
"You have unsaved changes are you sure you want to navigate away?": "Tem alterações não guardadas. Tem a certeza que quer sair?",
"Restore last draft": "Restaurar o último rascunho",
"Special character": "Carácter especial",
"Source code": "Código fonte",
"Language": "Idioma",
"Insert\/Edit code sample": "Inserir\/Editar amostra de código",
"B": "B",
"R": "V", // Vermelho (Red)
"G": "G", // Verde (Green)
"Color": "Cor",
"Right to left": "Direita para esquerda",
"Left to right": "Esquerda para direita",
"Emoticons": "Emoções",
"Robots": "Robôs",
"Document properties": "Propriedades do documento",
"Title": "Título",
"Keywords": "Palavras-chave",
"Encoding": "Codificação",
"Description": "Descrição",
"Author": "Autor",
"Fullscreen": "Ecrã completo",
"Horizontal line": "Linha horizontal",
"Horizontal space": "Espaço horizontal",
"Insert\/edit image": "Inserir\/editar imagem",
"General": "Geral",
"Advanced": "Avançado",
"Source": "Origem",
"Border": "Borda",
"Constrain proportions": "Manter proporções",
"Vertical space": "Espaço vertical",
"Image description": "Descrição da imagem",
"Style": "Estilo",
"Dimensions": "Dimensões",
"Insert image": "Inserir imagem",
"Image": "Imagem",
"Zoom in": "Aumentar zoom",
"Contrast": "Contraste",
"Back": "Voltar",
"Gamma": "Gama",
"Flip horizontally": "Inverter horizontalmente",
"Resize": "Redimensionar",
"Sharpen": "Nitidez",
"Zoom out": "Diminuir zoom",
"Image options": "Opções de imagem",
"Apply": "Aplicar",
"Brightness": "Brilho",
"Rotate clockwise": "Rodar no sentido horário",
"Rotate counterclockwise": "Rodar no sentido anti-horário",
"Edit image": "Editar imagem",
"Color levels": "Níveis de cor",
"Crop": "Recortar",
"Orientation": "Orientação",
"Flip vertically": "Inverter verticalmente",
"Invert": "Inverter",
"Date\/time": "Data\/hora",
"Insert date\/time": "Inserir data\/hora",
"Remove link": "Remover ligação",
"Url": "URL",
"Text to display": "Texto a exibir",
"Anchors": "Âncoras",
"Insert link": "Inserir ligação",
"Link": "Ligação",
"New window": "Nova janela",
"None": "Nenhum",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "O URL que inseriu parece ser uma ligação externa. Deseja adicionar o prefixo http:\/\/ necessário?",
"Paste or type a link": "Cole ou digite uma ligação",
"Target": "Alvo",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "O URL que inseriu parece ser um endereço de email. Deseja adicionar o prefixo mailto: necessário?",
"Insert\/edit link": "Inserir\/editar ligação",
"Insert\/edit video": "Inserir\/editar vídeo",
"Media": "Media",
"Alternative source": "Fonte alternativa",
"Paste your embed code below:": "Cole o código de incorporação abaixo:",
"Insert video": "Inserir vídeo",
"Poster": "Poster",
"Insert\/edit media": "Inserir\/editar media",
"Embed": "Incorporar",
"Nonbreaking space": "Espaço sem quebra",
"Page break": "Quebra de página",
"Paste as text": "Colar como texto",
"Preview": "Pré-visualizar",
"Print": "Imprimir",
"Save": "Guardar",
"Could not find the specified string.": "Não foi possível encontrar o texto especificado.",
"Replace": "Substituir",
"Next": "Seguinte",
"Whole words": "Palavras completas",
"Find and replace": "Localizar e substituir",
"Replace with": "Substituir por",
"Find": "Localizar",
"Replace all": "Substituir tudo",
"Match case": "Diferenciar maiúsculas/minúsculas",
"Prev": "Anterior",
"Spellcheck": "Verificação ortográfica",
"Finish": "Concluir",
"Ignore all": "Ignorar tudo",
"Ignore": "Ignorar",
"Add to Dictionary": "Adicionar ao dicionário",
"Insert row before": "Inserir linha antes",
"Rows": "Linhas",
"Height": "Altura",
"Paste row after": "Colar linha depois",
"Alignment": "Alinhamento",
"Border color": "Cor da borda",
"Column group": "Grupo de colunas",
"Row": "Linha",
"Insert column before": "Inserir coluna antes",
"Split cell": "Dividir célula",
"Cell padding": "Espaçamento interno",
"Cell spacing": "Espaçamento entre células",
"Row type": "Tipo de linha",
"Insert table": "Inserir tabela",
"Body": "Corpo",
"Caption": "Legenda",
"Footer": "Rodapé",
"Delete row": "Eliminar linha",
"Paste row before": "Colar linha antes",
"Scope": "Âmbito",
"Delete table": "Eliminar tabela",
"H Align": "Alinhamento H",
"Top": "Topo",
"Header cell": "Célula de cabeçalho",
"Column": "Coluna",
"Row group": "Grupo de linhas",
"Cell": "Célula",
"Middle": "Meio",
"Cell type": "Tipo de célula",
"Copy row": "Copiar linha",
"Row properties": "Propriedades da linha",
"Table properties": "Propriedades da tabela",
"Bottom": "Fundo",
"V Align": "Alinhamento V",
"Header": "Cabeçalho",
"Right": "Direita",
"Insert column after": "Inserir coluna depois",
"Cols": "Cols",
"Insert row after": "Inserir linha depois",
"Width": "Largura",
"Cell properties": "Propriedades da célula",
"Left": "Esquerda",
"Cut row": "Cortar linha",
"Delete column": "Eliminar coluna",
"Center": "Centro",
"Merge cells": "Unir células",
"Insert template": "Inserir modelo",
"Templates": "Modelos",
"Background color": "Cor de fundo",
"Custom...": "Personalizada...",
"Custom color": "Cor personalizada",
"No color": "Sem cor",
"Text color": "Cor do texto",
"Table of Contents": "Índice",
"Show blocks": "Mostrar blocos",
"Show invisible characters": "Mostrar caracteres invisíveis",
"Words: {0}": "Palavras: {0}",
"Insert": "Inserir",
"File": "Ficheiro",
"Edit": "Editar",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Área de Texto Rico. Pressione ALT-F9 para o menu. Pressione ALT-F10 para a barra de ferramentas. Pressione ALT-0 para ajuda.",
"Tools": "Ferramentas",
"View": "Ver",
"Table": "Tabela",
"Format": "Formato"
});